env:
  mode: live   # paper | live
  timezone: UTC

okx:
  # REST 主要用于冷启动回补（此处先留着）
  rest_base:
    live:  https://www.okx.com
    paper: https://eea.okx.com
  # WebSocket 域名
  ws:
    live:
      public:   wss://ws.okx.com:8443/ws/v5/public
      private:  wss://ws.okx.com:8443/ws/v5/private
      business: wss://ws.okx.com:8443/ws/v5/business
    paper:
      # 业务频道（如 mark-price-candle*）建议统一走 business
      business: wss://wspap.okx.com:8443/ws/v5/business
      public:   wss://wspap.okx.com:8443/ws/v5/public
      private:  wss://wseeapap.okx.com:8443/ws/v5/private

datafeed:
  instIds: ["ETH-USDT-SWAP", ] #"BTC-USDT-SWAP"]

  # 三类 K 线：trade / mark / index  → 映射到 candle / mark-price-candle / index-candle
  channels:
    candles:
      fetch: false
      kind: "trade"
      bars: ["1m","5m","4H"]
    trades:
      fetch: false
    books:
      fetch: false
      level: 400
    funding-rate:
      fetch: true
    open-interest:
      fetch: true
    

  ws_kind_per_channel:
    candles:      business
    trades:       public
    books:        public
    mark-price:   business
    funding-rate: public
    open-interest: public

  # 是否使用 business 域（订 mark-price/index-* 时通常为 true）
  use_business: true

  # 仅当订阅「需要登录」的频道或你主动要求时设为 true（纯行情一般 false）
  need_login: false

  # 按类型分别 flush
  flush_every_n:
    candle:  200
    trades:  400
    books:   200

  out_dir: "data/feed"
  store_backend: "csv"   # csv | parquet

auth:
  api_key: "${API_KEY}"
  secret_key: "${SECRET_KEY}"
  passphrase: "${PASSPHRASE}"