okx:
  # REST 主要用于冷启动回补（此处先留着）
  rest_base:
    live:  https://www.okx.com
    paper: https://eea.okx.com
  

  # WebSocket 域名
  ws:
    live:
      public:   wss://ws.okx.com:8443/ws/v5/public
      private:  wss://ws.okx.com:8443/ws/v5/private
      business: wss://ws.okx.com:8443/ws/v5/business
    paper:
      # 业务频道（如 mark-price-candle*）建议统一走 business
      business: wss://wspap.okx.com:8443/ws/v5/business
      public:   wss://wspap.okx.com:8443/ws/v5/public
      private:  wss://wseeapap.okx.com:8443/ws/v5/private

datafeed:
  instIds: ["BTC-USDT-SWAP", "ETH-USDT-SWAP"] #"BTC-USDT-SWAP"]

  # 三类 K 线：trade / mark / index  → 映射到 candle / mark-price-candle / index-candle
  channels:
    candles:
      fetch: true
      kind: "trade"
      bars: ["1m","15m","1H"]
    trades:
      fetch: true
    books:
      fetch: true
      level: 5
    funding-rate:
      fetch: true
    open-interest:
      fetch: true
    mark-price:
      fetch: false
    index-tickers:
      fetch: false
    liquidation-orders:
      instType: SWAP
      fetch: false
    price-limit:
      fetch: false
    
    
  ws_kind_per_channel:
    candles:      business
    trades:       public
    books:        public
    funding-rate: public
    open-interest: public
    mark-price: public
    index-tickers: public
    liquidation-orders: public
    price-limit: public

  # 是否使用 business 域（订 mark-price/index-* 时通常为 true）
  use_business: true

  # 仅当订阅「需要登录」的频道或你主动要求时设为 true（纯行情一般 false）
  need_login: false

  # 按类型分别 flush
  flush_every_n:
    candle:  200
    trades:  400
    books:   200

  out_dir: "data/feed"
  store_backend: "csv"   # csv | parquet

persist:
  csv_path: "data/features.csv"
  sqlite_path: "data/features.db"
  sqlite_table: "features"
  flush_interval_s: 5
  max_buffer_rows: 10

agent:
  min_snapshot_interval_ms: 600_000
  align_to_5m: false

cold_start:
  duration_sec: 600
  min_snapshots: 0

auth:
  api_key: "${API_KEY}"
  secret_key: "${SECRET_KEY}"
  passphrase: "${PASSPHRASE}"

trading:
  env: PAPER                # PAPER / LIVE
  simulated_header: true
  instType: SWAP
  symbols: [BTC-USDT-SWAP, ETH-USDT-SWAP]
  leverage: 5
  posMode: net              # net / long_short
  tdMode: cross             # cross / isolated
  slippage_bps: 10
  reconcile:
    poll_ms: 600
    timeout_ms: 5000
  ws:
    reconnect_backoff_ms: [500, 1000, 2000, 5000]
  timeouts:
    rest_ms: 3000
  retries:
    rest_max_attempts: 3
    backoff_ms: 200